"""Compare the two Rojo projects and emit tools/RemoveCandySync.studio.luau -- a command-bar
script that deletes every instance CandyRealm/default.project.json produces that the food
realm's default.project.json does NOT. Run after an accidental CandyRealm sync into the food place.

    python tools/gen_candy_cleanup.py
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUFFIX = re.compile(r"\.(server|client)?\.?(lua|luau)$")

def strip(name):
    # Foo.server.lua -> Foo ; Foo.client.luau -> Foo ; Foo.luau -> Foo
    n = re.sub(r"\.(server|client)\.(lua|luau)$", "", name)
    n = re.sub(r"\.(lua|luau)$", "", n)
    return n

def walk(node, path, base, out):
    """Collect instance paths (dot-joined, no DataModel) that the project tree produces."""
    p = node.get("$path")
    if p:
        full = os.path.join(base, p)
        if os.path.isdir(full):
            for f in sorted(os.listdir(full)):
                if f.endswith((".lua", ".luau")):
                    out.add(path + "." + strip(f) if path else strip(f))
        else:
            out.add(path)
    for k, v in node.items():
        if k.startswith("$"): continue
        child = path + "." + k if path else k
        if isinstance(v, dict):
            walk(v, child, base, out)

def load(proj_dir):
    with open(os.path.join(proj_dir, "default.project.json"), encoding="utf-8") as f:
        tree = json.load(f)["tree"]
    out = set()
    for k, v in tree.items():
        if k.startswith("$"): continue
        walk(v, k, proj_dir, out)
    return out

food  = load(ROOT)
candy = load(os.path.join(ROOT, "CandyRealm"))

# containers the projects declare (Shared folder etc.) are not scripts; drop anything that is a
# pure container in BOTH (they are fine to keep) and keep only leaf instances
candy_only = sorted(p for p in candy - food)
overlap    = sorted(p for p in candy & food)

luau = []
luau.append("--[[")
luau.append(" REMOVE THE ACCIDENTAL CANDYREALM SYNC  --  run in the FOOD REALM place, Studio Command Bar")
luau.append(" GENERATED by tools/gen_candy_cleanup.py from both default.project.json files.")
luau.append("")
luau.append(" CandyRealm's Rojo project was connected to this place by mistake. Rojo only ever ADDS, so every")
luau.append(" script CandyRealm ships now sits in this place beside the food realm's own. This deletes the")
luau.append(" %d instances that ONLY the CandyRealm project produces. The %d scripts BOTH projects produce" % (len(candy_only), len(overlap)))
luau.append(" (same name, same location) are NOT touched here -- they currently hold CandyRealm's code, and")
luau.append(" re-connecting the FOOD realm's `rojo serve` overwrites them back. Do that right after this runs.")
luau.append("")
luau.append(" Everything is done inside one ChangeHistory waypoint, so Ctrl+Z puts it all back.")
luau.append("]]")
luau.append("")
luau.append("local DRY_RUN = false -- true = only print what would be deleted")
luau.append("")
luau.append("local CANDY_ONLY = {")
for p in candy_only:
    luau.append('\t"%s",' % p)
luau.append("}")
luau.append("")
luau.append("-- Both projects produce these. Left alone; the food realm's rojo serve restores their source.")
luau.append("local SHARED_NAMES = {")
for p in overlap:
    luau.append('\t"%s",' % p)
luau.append("}")
luau.append(r'''
local CHS = game:GetService("ChangeHistoryService")

local function resolve(path)
	local cur = game
	for seg in string.gmatch(path, "[^%.]+") do
		cur = cur:FindFirstChild(seg)
		if not cur then return nil end
	end
	return cur
end

local removed, missing, skipped = 0, 0, 0
if not DRY_RUN then CHS:SetWaypoint("Before CandyRealm cleanup") end
for _, path in ipairs(CANDY_ONLY) do
	local inst = resolve(path)
	if not inst then
		missing += 1
	elseif not inst:IsA("LuaSourceContainer") then
		-- a Folder or something hand-made with the same name: not what Rojo put there, leave it
		warn(("[CandyCleanup] SKIP %s -- is a %s, not a script"):format(path, inst.ClassName))
		skipped += 1
	else
		print(("[CandyCleanup] %s %s (%s)"):format(DRY_RUN and "would delete" or "DELETED", path, inst.ClassName))
		if not DRY_RUN then inst:Destroy() end
		removed += 1
	end
end
if not DRY_RUN then CHS:SetWaypoint("After CandyRealm cleanup") end

print(("[CandyCleanup] %s: %d removed, %d already absent, %d skipped (not scripts)"):format(
	DRY_RUN and "DRY RUN" or "DONE", removed, missing, skipped))

-- the same-named ones: report which still carry CandyRealm code, judged by their header
local stale = 0
for _, path in ipairs(SHARED_NAMES) do
	local inst = resolve(path)
	if inst and inst:IsA("LuaSourceContainer") then
		local ok, src = pcall(function() return inst.Source end)
		if ok and src and (src:find("CandyRealm", 1, true) or src:find("Candy Realm", 1, true)) then
			stale += 1
			print(("[CandyCleanup] still CandyRealm code: %s  (re-sync from the FOOD project fixes it)"):format(path))
		end
	end
end
print(("[CandyCleanup] %d of %d shared-name scripts mention CandyRealm in their source. Connect the FOOD realm's rojo serve now, accept the sync, then re-run the boot and check [SECURITY] NOT-IN-MANIFEST is gone."):format(stale, #SHARED_NAMES))
''')

out = os.path.join(ROOT, "tools", "RemoveCandySync.studio.luau")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(luau))
print("candy-only:", len(candy_only))
for p in candy_only: print("  -", p)
print("overlap (re-sync restores):", len(overlap))
for p in overlap: print("  =", p)
print("wrote", out)
